sudo: required
dist: xenial
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script: python -m pytest
after_script: cd ~
deploy:
  provider: pypi
  user: baqs
  password:
    secure: SY66wAD/JaW1Xvl7dbn9ofeGYIo7W1mh6yZrg69U7RiHOVg0TbP9CaI7OZYh3VOPScswV3KlWdFZhYwqDPZEUfz1sUuI07dtYh1YtlBXLO3IxSwkvQJUthnoNx+4pHfQ8/ei3DLZaS6maGyfz3Pvqz7W1pzAGNApaCYHni/qqmI2iOk5lg/b1utggHEGBdjx4HHNT6KWOjX+jrs11kN6LCXtfj4yg02yVYIMEXtHg2LkChPIktWdM8njlCVx0aYq5jmYJAYGGzaT5hyLsx72/ns755pJrRn4Y4dOprtY0j2YKQV1LHs7keY7oOgguQMDq7KhvP7KNULU/zZtGypbYF6l3L71VkBrYYL9LcpAeK6r873EMq3Cl+eOq+MWtfCm1J9HFKpOQ4vfaYgD/Zx+GZ+1F0Ra1gNUAxh0C9SAX4PuzBEThd23tq/3WWJpaaprtchShTJmiKrhH7tICbFcuh3o7bOHzyZIHjIzxfs6XXoAwaxwgJT6tiFCoxWqpIahb9qim5haJUrMHiC5GkyQRJH1kYCeGCz/V0BCK+vxsl41e3P12xYzEzNGOdVladuFf+fzybUI+TrprvHIrNHapLIuyy1hsJCTzuc0v6lxafSZjWL3/khp+MbsjOeI34W+Tm+xqOm1a/RF5qsIrNADl0lhXeUtm1G+tQiZnHjg7aU=
