sudo: required
dist: xenial
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script: python -m pytest
after_script: cd ~
deploy:
  provider: pypi
  user: baqs
deployment:
  password:
    secure: MTuPwwZyNngJNgsOPmqRYqbosq339bCxh23r0LyqRd6MnI6aNI/wjW01SI2lbshPGQPN/x5EIMfxu+Ozg3nQWjTywvKJLo2ijVkY4983pu6yNZLlSPEViNFLLc1dACOc2dn7JKIdoa0pt7nHr2pBY6o4/L/iQHtMRvBRFubydL7yMwTmHOOYN4J2V+6FyCjMUDnakz+Ug1oEzE2gU8J4cx/ThHeFhxqBrKPgnQNxNQUz2YZEtVYGq6kqrDSWBmDpKMmDfK9xXo5o5iklR7zxgd58gJqIQt5/JlaWXP2KmL0DAAaIl+/bo/bwdp56gcEc6+faiSUWV33UZ8G5T9BkLeBoUaqitkVPU4ZV10N6N+EDyrBDyUROyNfg9lvIX6QTaic4UGxMZuRwSfbP9JYcdDl/RTiRjqujOtXSca0i/kRNEGQXEDHKxXaBusuneVODsojM1Ki6Ckm7erOUOy045ZAI+/EcpZOsMP8cMq/mjxY7bKbnpwsWIPGqVt4a12qfa5NrnEEMXXFw2+F6c62811kQ5wI97SamESk5+S5Rw9vf61hhnqldgI0dFjpwZLxsywsUkmswuAfGtJCbcDqRPuO2P23B39cFQGRWb7mZaFFPWfMKqfyOHV2WgM8qggXSyFx2+dPLIb+kQtxY48TchF/q8H6PqUJnZQhB0kD0K5U=
