sudo: required
dist: xenial
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script: python -m pytest
after_script: cd ~
deploy:
  provider: pypi
  user: baqs
  password:
    secure: OflWVNr5pcSAGaUgEm0nrnABMXeY/cSFTCKykFNH4xOh5ZdDFxYsKWlTNlUxGn1ksIm3WXBvdo6jSMDgPjZmFobo7AJ/NtU7H7ehcKpmaxWoVjIaccXG1GCxUmGlHWiN3QkygCvO/r+AopRda5sjfvf69LhWUJFRMI1MbHexYn0sn44Zrzmc6T4VnhDHG9C4QKnBOhFLClKUrgBlYOQPXHF7AEL7EhmYJBu9GNvsmqgOsXBUUKXcydgT4MEaG6NsyM0vYEJUz5Vya5Rf5yAwa6kzj7zofGzac5D23nuvBbosXbSYvT/uT6/NSJwb1t1zmqVadQY3TrOA/U/C+Jq6J0ThKE58Ym3uDev5ZlrdrXAaagzVM7YwnKJfk2+5adUk0H1iYJpfxq8yl+6oxvz74tKYiUXWV2scP2ciCerpunwbiimzIN+S/7UuS+rzN/3Mzfk/DmbKFJM9YayczGHgkuZLg8D/byLC4t3TceRPPCtXn3QhmLKg5HB2x7LOnSzkhd/BEroE8oFIWU9pEruHXQZlwDKi10FV4X1a4L5pJgmKgmxORLftQTJ0XCJks2jZtsiudE5BiwaqJcEl9jmDYG6X3sq6HvYgt3tU0q2dDh3BhdN7EmLu/8FTYdwkyIxvzkBkbAlTL7Cvfn2JWlJ0Guy7Sn6SXUuVEBrr7HM0daE=
