sudo: required
dist: xenial
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script: python -m pytest
after_script: cd ~
deploy:
  provider: pypi
  user: baqs
  password:
    secure: p53A4GW0+Q5dkqHNqqZq4FFIC5aimHV/NPOIaAp8PdltNHgQpGaynySpo/XqRhvTwv5yKrZQpW/1shiYyFjay+9Viym8VfN1GwmIg/nSgElvpWxTrix4h0SDgsAyRmzsZBnX/Xu1x10LE32muGdNDbe4wrLwzxgipk0uCS5SEpagwImmKCQkYO8Fjgfp3ENNsNGkOMFKTfJBmBrH6bcu7b2Ai22XnUCE+czlKFO/fBUscDCA3ctWHsIAhyIVacaWTHTPFUo+dgk7Y71EYy4aePcnoSGJ0HlD66puDArg5TMoEALAPZQmhJIDY5217JnRAHvUmeFCwA9esw5XzvgZ970wxk5ynplhJryckATuuDwS9es4QWMVbqrKgbaIxXL4ROa6auZEPi9vbma3Fiyt15f6rkI6Mb8uLa/9N7eLU+jfIxCX5vNbmThNhtKK5eloDJbW5arQ6ZUMxVL4nj4XFlSFVOgEsTc3cEsAfUnqdeR7EPyOM8utGyNHb5utBgxdeWS62kXdWbeP92Ac6czjVxOdNTEuFZXkc96crAS5yIXO/TVANCJEISYoBhgc57jcXSyMmt7PG7N7HsLmo2Zc+0wfPTplSfhe9bcC9DBtK/VJOEw3GkDAkFQntZw5ct4r25Gpbd2235NNGj1ztPm8Fn2BZl/RUXCB4swQxXa4ah8=
