sudo: required
dist: xenial
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script: python -m pytest
after_script: cd ~
deploy:
  provider: pypi
  user: baqs
  password:
    secure: YoirPghwKDiFcE46sBkEI/JokkpbeKYs/Ij66AxpRSDh0XDeru+j/Ep3XwRoVVQKUaNvksCAs24ZIM3FslzOGwxMBwB1TS36/boSdlj9VSaEppi4XdswKl1a+ek8C8I1rZUV3NseokVy3zAKkWcozdQpsPw58nNnPEpDFk0IeDRU1+Pn16zChO7cuQxoRPAri0ziTxEnhiLuUfb7enIb/HYFMcAs5Vk0lIKv3kmJHn6/Y3fQ1NEl5ZMWdkt41K/0q9YuiQg9Whzo78zACRv4cJnhG0EiKavnU98b6XVMt+8kcW6xhVBlxUBCjTSw32z2mwpY8lnSWifbTLlg12Ac1cabPRrTAfgdiFPsr+9dcQ3CvBE/+mCyi6PCHBctcwYYqDDuGHwb3kg6smW9Fnm3QRGd2/Rlz6mBCCvVl2/LoRMTi5XMaHtycSrNiIb8DgTsAF4SLhxNAyBf7gSN423iTcpTj1IXf2q109zvf0o02w8fqzsPctgZ/iM97GzHmaYwsfOYa4UxG+C6Ao1NMb2W50nEH2vkX43SIbU7nTe1J5go9v9XaP1yXzqlAF48PsMHkLt9ngnqMZmsC62js/SVFWxvHSWB70BrRoHzu4+RaYlSlegceaPqWMQl/bE3rdhv1AwDtOOznF+6BpfIxEvTNbZ6UAVrLKz02YURw+AWdcE=
