sudo: required
dist: xenial
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script: python -m pytest
after_script: cd ~
deploy:
  provider: pypi
  user: baqs
  password:
    secure: h+O4ZteFjM7FV3h63f9mZEwxhj6KUmjEW9WXbMW1ZLGVGd94NNYKfRqp3K9Gzl4O0vwDtbAWdzdyZbniE19izIY50pA3schMZD5jRNAXQKoyJN3fpNn00MChMb92TedFBNSFpxUY1GDGaD6W+3GvASiZB+29cUYmmg+eZ2CvmdYTLrHsGBy7ss3jwiZLGlivrRA1mKm8euV5fh5DFzTK9LdA63J+WST/s7+lCSiPp6R4C8xVrGWGL5P8uvlEP55jLi5uYsWeOdaoPQfERNcblzIJaDK8ayxC5ytXGfLOueqDpHQ+UytPNJEJ24HDT5QTWWwXWHvEq9dmKllEbUrLRbNkIPmiNmoMeR0Jpsv1Yyfn63N3kOJhoTjm52nXaxBFuWG/v6bvrMs40rLrKL1DytxnFwnaD99dR/uyFO8NF2a1atcShX5E9GJIWVqLBXIGDi+OfMTkkELfGPEoyNBgjlR0uqC8Z/2r1/3IsQ0ZmdpuEuzvxeJEAdYGc9ah6cPISojxF7hbWweQHC0tZ9lt0NNLNCkI58Payc5lW3jk2gLA2Uac33IhEfZMBbh0ynUTDIMEmrVgZLGol7upilUMwqi1vpLlOa+fGv/5Woc1jkdncgaIqW64WeI6OqW3pjCPbAFMqSE0mA+eejzsF3B8aPZvdu72BTQHKQ2f0Pe+aPg=
